# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaying < Formula
  desc "Cross-platform Now Playing TUI for Spotify, Apple Music, and more"
  homepage "https://github.com/justinmdickey/goplaying"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.2/goplaying_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "37274af230046d90e508e79c2e3e9ba79054b7cc853e6d3461baf40bf66561b9"

      def install
        bin.install "goplaying"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.2/goplaying_0.3.2_Darwin_arm64.tar.gz"
      sha256 "4bb0fc458f92bc4ebdd2ac72d437639fca4108b15a1e83db7e5bc85688d70f24"

      def install
        bin.install "goplaying"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.2/goplaying_0.3.2_Linux_x86_64.tar.gz"
      sha256 "7e1d1a83da808be4d37b0f231865b851286d4bd7254a757dc16547257eb8bc45"
      def install
        bin.install "goplaying"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.2/goplaying_0.3.2_Linux_arm64.tar.gz"
      sha256 "f1dbc59ae937af63caa00c984362b1bd20bf48c76b53867218366888d9848ab0"
      def install
        bin.install "goplaying"
      end
    end
  end

  def caveats
    <<~EOS
      macOS:
        - Album artwork works with Spotify and Apple Music via AppleScript
        - For broader app support (Safari, Chrome, etc.), build the Swift helper with 'make darwin'
      Linux:
        - Requires playerctl to be installed separately
        - Album artwork works with any MPRIS player that provides artwork
    EOS
  end

  test do
    system "#{bin}/goplaying", "--version"
  end
end
