# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goplaying < Formula
  desc "Cross-platform Now Playing TUI for Spotify, Apple Music, and more"
  homepage "https://github.com/justinmdickey/goplaying"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.0/goplaying_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "d07b93e79fc4404cfe785cfc0f19eff048e4ed55e15bcab3bed8d906d9f631f8"

      def install
        bin.install "goplaying"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.0/goplaying_0.3.0_Darwin_arm64.tar.gz"
      sha256 "19c275f29c4c037af7acfcf0d2e1b0d0f5bc5e5fb11d07135ecbcdf02d5ada81"

      def install
        bin.install "goplaying"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.0/goplaying_0.3.0_Linux_x86_64.tar.gz"
      sha256 "0681a15e35fade2b3a682cb9b928ae1978bde6549346b0dba04f9890aab2bbdf"
      def install
        bin.install "goplaying"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/justinmdickey/goplaying/releases/download/v0.3.0/goplaying_0.3.0_Linux_arm64.tar.gz"
      sha256 "516e212a27f542e3fc64e5668e6870375983858119be170c6aa267599838ac3a"
      def install
        bin.install "goplaying"
      end
    end
  end

  def caveats
    <<~EOS
      macOS:
        - Album artwork works with Spotify and Apple Music via AppleScript
        - For broader app support (Safari, Chrome, etc.), build the Swift helper with 'make darwin'
      Linux:
        - Requires playerctl to be installed separately
        - Album artwork works with any MPRIS player that provides artwork
    EOS
  end

  test do
    system "#{bin}/goplaying", "--version"
  end
end
